import { RecentSignup, UpcomingClass } from "@/features/dashboard/types";

export const MOCK_RECENT_SIGNUPS: RecentSignup[] = [
  {
    id: "1",
    name: "Christy",
    avatar: "/christy.png",
    joinedAt: "2 days ago",
    role: "member",
  },
  {
    id: "2",
    name: "helen micheal",
    avatar: "/helen micheal.jpg",
    joinedAt: "18 seconds ago",
    role: "member",
  },
  {
    id: "3",
    name: "john mark",
    avatar: "/john mark.png",
    joinedAt: "1 minute ago",
    role: "member",
  },
  {
    id: "4",
    name: "paul smith",
    avatar: "/paul smith.jpg",
    joinedAt: "1 hour ago",
    role: "member",
  },
  {
    id: "5",
    name: "trevor rowland",
    avatar: "/trevor rowland.jpg",
    joinedAt: "1 week ago",
    role: "member",
  },
  {
    id: "6",
    name: "ken ben",
    avatar: "/ken ben.jpg",
    joinedAt: "3 days ago",
    role: "member",
  },
  {
    id: "7",
    name: "helen micheal",
    avatar: "/helen micheal.jpg",
    joinedAt: "20 minutes ago",
    role: "member",
  },
  {
    id: "8",
    name: "rowland boy",
    avatar: "/paul smith.jpg",
    joinedAt: "5 hours ago",
    role: "member",
  },
  {
    id: "9",
    name: "Arnold swarzenneger",
    avatar: "/arnold.png",
    joinedAt: "5 seconds ago",
    role: "member",
  },
  {
    id: "10",
    name: "Christian",
    avatar: "/christy.png",
    joinedAt: "10 minutes ago",
    role: "member",
  },
];

export const MOCK_UPCOMING_CLASSES: UpcomingClass[] = [
  {
    id: "1",
    name: "Yoga class",
    time: "2:00 AM - 3:00 AM",
    trainer: "Susan wellson",
    capacity: 5,
    enrolled: 3,
    status: "upcoming",
  },
  {
    id: "2",
    name: "Pilates session",
    time: "10:00 AM - 11:00 AM",
    trainer: "Susan wellson",
    capacity: 8,
    enrolled: 8,
    status: "ongoing",
  },
  {
    id: "3",
    name: "Cardio workout",
    time: "3:30 PM - 4:30 PM",
    trainer: "Susan wellson",
    capacity: 12,
    enrolled: 9,
    status: "upcoming",
  },
  {
    id: "4",
    name: "Meditation class",
    time: "6:00 AM - 7:00 AM",
    trainer: "Susan wellson",
    capacity: 6,
    enrolled: 4,
    status: "upcoming",
  },
  {
    id: "5",
    name: "Zumba dance",
    time: "5:30 PM - 6:30 PM",
    trainer: "Susan wellson",
    capacity: 10,
    enrolled: 10,
    status: "ongoing",
  },
  {
    id: "6",
    name: "Strength training",
    time: "8:00 AM - 9:00 AM",
    trainer: "Susan wellson",
    capacity: 7,
    enrolled: 5,
    status: "upcoming",
  },
  {
    id: "7",
    name: "Spinning class",
    time: "1:00 PM - 2:00 PM",
    trainer: "Susan wellson",
    capacity: 9,
    enrolled: 7,
    status: "upcoming",
  },
  {
    id: "8",
    name: "Piloxing session",
    time: "4:00 PM - 5:00 PM",
    trainer: "Susan wellson",
    capacity: 8,
    enrolled: 8,
    status: "ongoing",
  },
  {
    id: "9",
    name: "HIIT workout",
    time: "9:30 AM - 10:30 AM",
    trainer: "Susan wellson",
    capacity: 5,
    enrolled: 5,
    status: "ongoing",
  },
  {
    id: "10",
    name: "Barre exercise",
    time: "7:30 PM - 8:30 PM",
    trainer: "Susan wellson",
    capacity: 10,
    enrolled: 6,
    status: "upcoming",
  },
  {
    id: "11",
    name: "Kickboxing",
    time: "12:00 PM - 1:00 PM",
    trainer: "Susan wellson",
    capacity: 10,
    enrolled: 8,
    status: "upcoming",
  },
  {
    id: "12",
    name: "Yoga for Beginners",
    time: "11:00 AM - 12:00 PM",
    trainer: "Susan wellson",
    capacity: 8,
    enrolled: 8,
    status: "ongoing",
  },
  {
    id: "13",
    name: "Prenatal Yoga",
    time: "6:30 AM - 7:30 AM",
    trainer: "Susan wellson",
    capacity: 4,
    enrolled: 2,
    status: "upcoming",
  },
  {
    id: "14",
    name: "Aerobics",
    time: "3:00 PM - 4:00 PM",
    trainer: "Susan wellson",
    capacity: 12,
    enrolled: 10,
    status: "upcoming",
  },
  {
    id: "15",
    name: "Functional Fitness",
    time: "7:00 AM - 8:00 AM",
    trainer: "Susan wellson",
    capacity: 10,
    enrolled: 10,
    status: "ongoing",
  },
  {
    id: "16",
    name: "Dance Fusion",
    time: "2:30 PM - 3:30 PM",
    trainer: "Susan wellson",
    capacity: 15,
    enrolled: 11,
    status: "upcoming",
  },
  {
    id: "17",
    name: "CrossFit",
    time: "5:00 PM - 6:00 PM",
    trainer: "Susan wellson",
    capacity: 12,
    enrolled: 9,
    status: "upcoming",
  },
  {
    id: "18",
    name: "Circuit Training",
    time: "8:30 AM - 9:30 AM",
    trainer: "Susan wellson",
    capacity: 8,
    enrolled: 8,
    status: "ongoing",
  },
  {
    id: "19",
    name: "Stretching Session",
    time: "1:30 PM - 2:30 PM",
    trainer: "Susan wellson",
    capacity: 6,
    enrolled: 4,
    status: "upcoming",
  },
  {
    id: "20",
    name: "Bodyweight Exercises",
    time: "4:30 PM - 5:30 PM",
    trainer: "Susan wellson",
    capacity: 10,
    enrolled: 7,
    status: "upcoming",
  },
  {
    id: "21",
    name: "High-Intensity Interval Training",
    time: "8:30 PM - 9:30 PM",
    trainer: "Susan wellson",
    capacity: 10,
    enrolled: 6,
    status: "upcoming",
  },
];

export const INITIAL_STATS = {
  totalMembers: 1480,
  totalTrainers: 20,
  activeClasses: 45,
  revenue: 8500000,
  recentSignups: [],
  upcomingClasses: [],
  capacityUsage: 67,
  revenueData: [120000, 190000, 300000, 250000, 420000, 380000, 500000],
};
